import Leftbar from '@/components/Leftbar'
import Navbar from '@/components/Navbar'
import Posts from '@/components/Posts'
import Rightbar from '@/components/Rightbar'
import axios from 'axios'
import Head from 'next/head'
import { useEffect, useState } from 'react'
import Login from './login'
import jwt from 'jsonwebtoken';

export async function getServerSideProps(context) {

  try {
    const res = await axios.get(`${process.env.NEXT_PUBLIC_URL}/api/post`,
      { withCredentials: true }
    );

    const token = context.req.cookies.access_token;

    if (!token) throw new Error("Invalid token");

    const payload = jwt.verify(token, process.env.JWT_KEY);

    if (!payload.user_id) throw new Error("Invalid");

    return {
      props: {
        postData: res?.data || [],
        isAuth: true,
      }
    }

  } catch (error) {
    return {
      props: {
        postData: [],
        isAuth: false,
      }
    }
  }
}

export default function Home({ postData, isAuth }) {

  const [modal, setModal] = useState(false);

  useEffect(() => {
    !isAuth && localStorage.clear();
  }, []);

  return (
    <>
      <Head>
        <title>Social App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {isAuth ?
        <div
          onLoad={e => {
            const scrol = document.querySelector('body');
            scrol.scrollIntoView({
              behavior: 'auto'
            }, 0)
          }}
        >

          <Navbar setModal={setModal} />

          <div className='flex'>

            <div className='flex-[0] lg:flex-[2]'>
              <Leftbar />
            </div>

            <div className='flex-[12] lg:flex-[6]'>
              <Posts postData={postData} modal={modal} />
            </div>

            <div className='flex-[0] lg:flex-[4]'>
              <Rightbar />
            </div>

          </div>

        </div>
        :
        <Login />
      }

    </>
  )
}
